/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{vue,js}"],
  theme: {
    extend: {
      colors: {
        surface: "#17130d",
        "surface-dim": "#17130d",
        "surface-bright": "#3e3831",
        "surface-container-lowest": "#110e08",
        "surface-container-low": "#1f1b14",
        "surface-container": "#231f18",
        "surface-container-high": "#2e2922",
        "surface-container-highest": "#39342d",
        "on-surface": "#ebe1d6",
        "on-surface-variant": "#d0c5b5",
        outline: "#999081",
        "outline-variant": "#4d463a",
        primary: "#e1c386",
        "on-primary": "#402d00",
        "primary-container": "#a88d56",
        "primary-fixed": "#ffdfa0",
        "primary-fixed-dim": "#e1c386",
        secondary: "#d9c4a0",
        "on-secondary": "#3b2f15",
        "secondary-container": "#55472c",
        tertiary: "#f8b990",
        "on-tertiary": "#4d2609",
        "tertiary-container": "#bc845f",
        "tertiary-fixed": "#ffdcc7",
        "tertiary-fixed-dim": "#f8b990",
        background: "#17130d",
        "on-background": "#ebe1d6",
        error: "#ffb4ab",
        "error-container": "#93000a",
      },
      fontFamily: {
        sans: ["Public Sans", "Noto Sans TC", "sans-serif"],
        chinese: ["Noto Sans TC", "sans-serif"],
      },
      fontSize: {
        "headline-lg": ["40px", { lineHeight: "52px", fontWeight: "700" }],
        "headline-md": ["32px", { lineHeight: "42px", fontWeight: "600" }],
        "body-lg": ["22px", { lineHeight: "34px", fontWeight: "400" }],
        "body-md": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "label-lg": [
          "20px",
          { lineHeight: "24px", fontWeight: "600", letterSpacing: "0.02em" },
        ],
      },
      borderRadius: {
        DEFAULT: "0.5rem",
        sm: "0.25rem",
        md: "0.75rem",
        lg: "1rem",
        xl: "1.5rem",
        full: "9999px",
      },
      spacing: {
        "touch-target-min": "56px",
        "margin-edge": "24px",
        gutter: "16px",
        "stack-gap": "20px",
      },
    },
  },
  plugins: [],
};
